### ISSUE TITLE
We are facing an issue while installing it even my .NET framework version is 4.5.2

### ISSUE THREAD

**Issue by Rahulraj04** [chriswill/RippleDotNet#2]
The project does not contain any assembly references or content files that are compatible with that frameworks

**Comment by chriswill** [comment]
This is a .Net Standard 2.0 implementation.  To call it using a .Net Framework application, you have to be running at least [.Net 4.6.1](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).
