### ISSUE TITLE
Transaction type “AccounDelete” Isn’t Exist

### ISSUE THREAD

**Issue by emre-pehlivan** [chriswill/RippleDotNet#5]
Hi,
I have added a pullrequest for this topic (#4 ). Can you review?

**Comment by farukterzioglu** [comment]
Waiting this to be merged

**Comment by chriswill** [comment]
Would you like to have this lib published to nuget?

**Comment by farukterzioglu** [comment]
It would be help us a lot, otherwise we will fork this and create our own nuget package

**Comment by chriswill** [comment]
This is now published on Nuget  https://www.nuget.org/packages/RippleCoreAPI/.

**Comment by chriswill** [comment]
I changed the nuget package name to https://www.nuget.org/packages/Ripple.APICore/
