### ISSUE TITLE
1.9.0 rippled - method AccountTransactions hangs - nft - transactions

### ISSUE THREAD

**Issue by BruceHunter** [chriswill/RippleDotNet#8]
- Address with NFT Transactions: **rfFbVpiimxqkQufGcrQfqnz15h2xPBfk3g**

When calling signatures->
```
private IRippleClient _client;
_client.AccountTransactions(transactionsRequest);
_client.AccountTransactions(accountAddress);
```

The methods "hang" and don't seem to return anything.

Please add support for 1.9.0 rippled if not already.

**Comment by chriswill** [comment]
Bruce, thanks for the message, but I'm not really active in Ripple any longer.  You're welcome to submit a pull request, or fork this and continue.

**Comment by BruceHunter** [comment]
Thank you very much for responding.

Yeah, looks like the 

` private void MessageReceived(string s, WebSocketClient client)`

method is throwing an exception for missing TransactionTypes + Serialization to the Reponse types.
